### ISSUE TITLE
400 Bad request on text with \n

### ISSUE THREAD

**Issue by Doooooo0o** [vgallissot/jamaicanize#2]
I can't send newline in input to jamaicanize a huge text :

```
./jamaicanize.py "my ham is \n rich"
Traceback (most recent call last):
  File "./jamaicanize.py", line 20, in <module>
    html = urlopen("http://www.jamaicantranslator.com/?english=" + sentence)
  File "/usr/lib64/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib64/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib64/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request
```

**Comment by vgallissot** [comment]
You must see that as a wrapper instead of a cli.
Everything you cannot send to **http://www.jamaicantranslator.com** won't work from this tool neither.

I just can suggest you call it for each line you need ;)
BR

**Comment by vgallissot** [comment]
I'd be a good enhancement to:
1. encode input text so that it could be send over HTTP GET requests. I tried it with html.escape but doesn't seem to work.
2. Add a try-catch so unsupported request can fail cleanly
